### ISSUE TITLE
Clarification Needed on Pretrained Model Selection in model_for_pretrain.py

### ISSUE THREAD

**Issue by HAMMAD-Shahid27** [Hydragon516/GSANet#7]
Hello,

Thank you for sharing this great work and making it publicly available!

I noticed that in the paper, the pretrained model is mentioned as NVIDIA MiT-B2, but in the model_for_ pretrain.py script, the code appears to download the pretrained NVIDIA MiT-B1 model instead.

Could you please clarify if this is an intentional choice or if it might be an oversight? Understanding this detail will help ensure the implementation aligns with the methodology described in the paper.

Thank you for your time and for the valuable contribution!

**Comment by Hydragon516** [comment]
Thank you for identifying the code bug.
We have identified and corrected the incorrectly entered code from a previous ablation study.

**Comment by HAMMAD-Shahid27** [comment]
I wanted to sincerely thank you for promptly addressing and fixing the
bug. Your efforts are greatly appreciated and have made a significant
difference.
 I need one more clarification on Image size in config.py for simple
training and testing without test time augmentation. Value of image aize is
384 or 512 Because the thing i understand through the code is to set all
RGB and optical flow maps are set to 384.
Thank you again for your time and support.
